<a href="https://colab.research.google.com/github/Neeti-Jain/Machine-Learning/blob/master/CustomerSegmentation/CustomerSegmentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import files
#files.upload()

In [0]:
!mkdir -p ~/.kaggle

In [0]:
!cp kaggle.json ~/.kaggle/

In [0]:
!chmod 600 ~/.kaggle/kaggle.json

In [77]:
!ls ~/.kaggle

kaggle.json

In [78]:
!ls -l ~/.kaggle

total 4
-rw------- 1 root root 65 Feb 24 18:25 kaggle.json

In [79]:
!cat ~/.kaggle/kaggle.json

{"username":"neetijain","key":"7a8d263c2058773b1d68f2dc4af9d917"}

In [0]:
!pip install -q kaggle

In [0]:
!pip install -q kaggle-cli

In [82]:
!kaggle datasets list

ref                                                          title                                                size  lastUpdated          downloadCount
-----------------------------------------------------------  --------------------------------------------------  -----  -------------------  -------------
lava18/google-play-store-apps                                Google Play Store Apps                                2MB  2019-02-03 13:55:47          37742
ronitf/heart-disease-uci                                     Heart Disease UCI                                     3KB  2018-06-25 11:33:56           9273
karangadiya/fifa19                                           FIFA 19 complete player dataset                       2MB  2018-12-21 03:52:59           9865
vjchoudhary7/customer-segmentation-tutorial-in-python        Mall Customer Segmentation Data                       2KB  2018-08-11 07:23:02           2887
cityofLA/los-angeles-parking-citations                       Los Angeles Parking Citations                       245MB  2019-02-21 22:20:03           1829
russellyates88/suicide-rates-overview-1985-to-2016           Suicide Rates Overview 1985 to 2016                 396KB  2018-12-01 19:18:25           6447
bigquery/crypto-ethereum-classic                             Ethereum Classic Blockchain                          66GB  2019-02-05 17:41:48              0
mohansacharya/graduate-admissions                            Graduate Admissions                                   9KB  2018-12-28 10:07:14          10449
iarunava/cell-images-for-detecting-malaria                   Malaria Cell Images Dataset                         337MB  2018-12-05 05:40:21           1802
noriuk/us-education-datasets-unification-project             U.S. Education Datasets: Unification Project         84MB  2018-12-22 17:09:05           1387
jessicali9530/stanford-dogs-dataset                          Stanford Dogs Dataset                               735MB  2019-02-13 05:45:25            565
safegraph/census-block-group-american-community-survey-data  Census Block Group American Community Survey Data     2GB  2018-12-22 00:29:56            339
jessicali9530/celeba-dataset                                 CelebFaces Attributes (CelebA) Dataset                1GB  2018-06-01 20:08:48           4321
safegraph/visit-patterns-by-census-block-group               Consumer & Visitor Insights For Neighborhoods        66MB  2018-12-19 21:31:50            535
jutrera/stanford-car-dataset-by-classes-folder               Stanford Car Dataset by classes folder                2GB  2018-07-02 07:35:45           1767
rmisra/news-headlines-dataset-for-sarcasm-detection          News Headlines Dataset For Sarcasm Detection          2MB  2018-06-09 22:14:56           1298
mdhrumil/top-5000-youtube-channels-data-from-socialblade     Top 5000 Youtube channels data from Socialblade.    128KB  2018-09-09 14:05:54           3325
fivethirtyeight/fivethirtyeight-comic-characters-dataset     FiveThirtyEight Comic Characters Dataset            577KB  2019-02-01 15:02:23           1183
anokas/kuzushiji                                             Kuzushiji-MNIST                                     318MB  2018-12-17 01:19:31            421
pavansanagapati/urban-sound-classification                   Urban Sound Classification                            6GB  2018-06-16 13:44:36           1454

In [83]:
!kaggle competitions list

ref                                            deadline             category            reward  teamCount  userHasEntered
---------------------------------------------  -------------------  ---------------  ---------  ---------  --------------
digit-recognizer                               2030-01-01 00:00:00  Getting Started  Knowledge       2498           False
titanic                                        2030-01-01 00:00:00  Getting Started  Knowledge       9930           False
house-prices-advanced-regression-techniques    2030-01-01 00:00:00  Getting Started  Knowledge       4097           False
imagenet-object-localization-challenge         2029-12-31 07:00:00  Research         Knowledge         35           False
competitive-data-science-predict-future-sales  2019-12-31 23:59:00  Playground           Kudos       2392           False
two-sigma-financial-news                       2019-07-15 23:59:00  Featured          $100,000       2927           False
LANL-Earthquake-Prediction                     2019-06-03 23:59:00  Research           $50,000       1308           False
tmdb-box-office-prediction                     2019-05-30 23:59:00  Playground       Knowledge        265           False
dont-overfit-ii                                2019-05-07 23:59:00  Playground            Swag        741           False
gendered-pronoun-resolution                    2019-04-22 23:59:00  Research           $25,000        243           False
santander-customer-transaction-prediction      2019-04-10 23:59:00  Featured           $65,000       2241           False
womens-machine-learning-competition-2019       2019-04-09 23:59:00  Featured           $25,000         90           False
mens-machine-learning-competition-2019         2019-04-08 23:59:00  Featured           $25,000        147           False
histopathologic-cancer-detection               2019-03-30 23:59:00  Playground       Knowledge        712           False
petfinder-adoption-prediction                  2019-03-28 23:59:00  Featured           $25,000       1293           False
vsb-power-line-fault-detection                 2019-03-21 23:59:00  Featured           $25,000       1039           False
microsoft-malware-prediction                   2019-03-13 23:59:00  Research           $25,000       1909           False
humpback-whale-identification                  2019-02-28 23:59:00  Featured           $25,000       2071           False
elo-merchant-category-recommendation           2019-02-26 23:59:00  Featured           $50,000       4144           False
ga-customer-revenue-prediction                 2019-02-21 20:04:00  Featured           $45,000       1100           False

In [84]:
!kaggle datasets download -d carrie1/ecommerce-data

ecommerce-data.zip: Skipping, found more recently modified local copy (use --force to force download)

In [85]:
!unzip -d ecomm ecommerce-data.zip

Archive:  ecommerce-data.zip
replace ecomm/data.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n

In [86]:
import pandas as pd
from datetime import datetime

infile=pd.read_csv('ecomm/data.csv',encoding='ISO-8859-1')
(infile.columns)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [87]:
#Converting the format of Date to another format
infile['InvoiceDate']=infile['InvoiceDate'].apply(lambda x:datetime.strptime(x, '%m/%d/%Y %H:%M').strftime('%Y-%m-%d'))
print(infile.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

  InvoiceDate  UnitPrice  CustomerID         Country
0  2010-12-01       2.55     17850.0  United Kingdom
1  2010-12-01       3.39     17850.0  United Kingdom
2  2010-12-01       2.75     17850.0  United Kingdom
3  2010-12-01       3.39     17850.0  United Kingdom
4  2010-12-01       3.39     17850.0  United Kingdom

In [88]:
p=infile['InvoiceDate'].min()
print('min',p)
q=infile['InvoiceDate'].max()
print('max',q)

min 2010-12-01
max 2011-12-09

In [89]:
infile

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01,4.25,13047.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,2010-12-01,4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01,5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01,5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01,7.95,13047.0,United Kingdom
20,536367,48187,DOORMAT NEW ENGLAND,4,2010-12-01,7.95,13047.0,United Kingdom
21,536368,22960,JAM MAKING SET WITH JARS,6,2010-12-01,4.25,13047.0,United Kingdom
22,536368,22913,RED COAT RACK PARIS FASHION,3,2010-12-01,4.95,13047.0,United Kingdom
23,536368,22912,YELLOW COAT RACK PARIS FASHION,3,2010-12-01,4.95,13047.0,United Kingdom
24,536368,22914,BLUE COAT RACK PARIS FASHION,3,2010-12-01,4.95,13047.0,United Kingdom
25,536369,21756,BATH BUILDING BLOCK WORD,3,2010-12-01,5.95,13047.0,United Kingdom
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01,3.75,12583.0,France
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01,3.75,12583.0,France
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01,3.75,12583.0,France
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01,0.85,12583.0,France
...,...,...,...,...,...,...,...,...
541879,581585,22726,ALARM CLOCK BAKELIKE GREEN,8,2011-12-09,3.75,15804.0,United Kingdom
541880,581585,22727,ALARM CLOCK BAKELIKE RED,4,2011-12-09,3.75,15804.0,United Kingdom
541881,581585,16016,LARGE CHINESE STYLE SCISSOR,10,2011-12-09,0.85,15804.0,United Kingdom
541882,581585,21916,SET 12 RETRO WHITE CHALK STICKS,24,2011-12-09,0.42,15804.0,United Kingdom
541883,581585,84692,BOX OF 24 COCKTAIL PARASOLS,25,2011-12-09,0.42,15804.0,United Kingdom
541884,581585,84946,ANTIQUE SILVER T-LIGHT GLASS,12,2011-12-09,1.25,15804.0,United Kingdom
541885,581585,21684,SMALL MEDINA STAMPED METAL BOWL,12,2011-12-09,0.85,15804.0,United Kingdom
541886,581585,22398,MAGNETS PACK OF 4 SWALLOWS,12,2011-12-09,0.39,15804.0,United Kingdom
541887,581585,23328,SET 6 SCHOOL MILK BOTTLES IN CRATE,4,2011-12-09,3.75,15804.0,United Kingdom
541888,581585,23145,ZINC T-LIGHT HOLDER STAR LARGE,12,2011-12-09,0.95,15804.0,United Kingdom
541889,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,2011-12-09,1.95,15804.0,United Kingdom
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,2011-12-09,2.95,13113.0,United Kingdom
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,2011-12-09,1.25,13113.0,United Kingdom
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09,8.95,13113.0,United Kingdom
541893,581586,20685,DOORMAT RED RETROSPOT,10,2011-12-09,7.08,13113.0,United Kingdom
541894,581587,22631,CIRCUS PARADE LUNCH BOX,12,2011-12-09,1.95,12680.0,France
541895,581587,22556,PLASTERS IN TIN CIRCUS PARADE,12,2011-12-09,1.65,12680.0,France
541896,581587,22555,PLASTERS IN TIN STRONGMAN,12,2011-12-09,1.65,12680.0,France
541897,581587,22728,ALARM CLOCK BAKELIKE PINK,4,2011-12-09,3.75,12680.0,France
541898,581587,22727,ALARM CLOCK BAKELIKE RED,4,2011-12-09,3.75,12680.0,France
541899,581587,22726,ALARM CLOCK BAKELIKE GREEN,4,2011-12-09,3.75,12680.0,France
541900,581587,22730,ALARM CLOCK BAKELIKE IVORY,4,2011-12-09,3.75,12680.0,France
541901,581587,22367,CHILDRENS APRON SPACEBOY DESIGN,8,2011-12-09,1.95,12680.0,France
541902,581587,22629,SPACEBOY LUNCH BOX,12,2011-12-09,1.95,12680.0,France
541903,581587,23256,CHILDRENS CUTLERY SPACEBOY,4,2011-12-09,4.15,12680.0,France
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09,4.95,12680.0,France

In [90]:

#infile=infile['CustomerID'].dropna()
infile.dropna(subset=['CustomerID'],inplace=True)
infile

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01,4.25,13047.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,2010-12-01,4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01,5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01,5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01,7.95,13047.0,United Kingdom
20,536367,48187,DOORMAT NEW ENGLAND,4,2010-12-01,7.95,13047.0,United Kingdom
21,536368,22960,JAM MAKING SET WITH JARS,6,2010-12-01,4.25,13047.0,United Kingdom
22,536368,22913,RED COAT RACK PARIS FASHION,3,2010-12-01,4.95,13047.0,United Kingdom
23,536368,22912,YELLOW COAT RACK PARIS FASHION,3,2010-12-01,4.95,13047.0,United Kingdom
24,536368,22914,BLUE COAT RACK PARIS FASHION,3,2010-12-01,4.95,13047.0,United Kingdom
25,536369,21756,BATH BUILDING BLOCK WORD,3,2010-12-01,5.95,13047.0,United Kingdom
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01,3.75,12583.0,France
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01,3.75,12583.0,France
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01,3.75,12583.0,France
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01,0.85,12583.0,France
...,...,...,...,...,...,...,...,...
541879,581585,22726,ALARM CLOCK BAKELIKE GREEN,8,2011-12-09,3.75,15804.0,United Kingdom
541880,581585,22727,ALARM CLOCK BAKELIKE RED,4,2011-12-09,3.75,15804.0,United Kingdom
541881,581585,16016,LARGE CHINESE STYLE SCISSOR,10,2011-12-09,0.85,15804.0,United Kingdom
541882,581585,21916,SET 12 RETRO WHITE CHALK STICKS,24,2011-12-09,0.42,15804.0,United Kingdom
541883,581585,84692,BOX OF 24 COCKTAIL PARASOLS,25,2011-12-09,0.42,15804.0,United Kingdom
541884,581585,84946,ANTIQUE SILVER T-LIGHT GLASS,12,2011-12-09,1.25,15804.0,United Kingdom
541885,581585,21684,SMALL MEDINA STAMPED METAL BOWL,12,2011-12-09,0.85,15804.0,United Kingdom
541886,581585,22398,MAGNETS PACK OF 4 SWALLOWS,12,2011-12-09,0.39,15804.0,United Kingdom
541887,581585,23328,SET 6 SCHOOL MILK BOTTLES IN CRATE,4,2011-12-09,3.75,15804.0,United Kingdom
541888,581585,23145,ZINC T-LIGHT HOLDER STAR LARGE,12,2011-12-09,0.95,15804.0,United Kingdom
541889,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,2011-12-09,1.95,15804.0,United Kingdom
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,2011-12-09,2.95,13113.0,United Kingdom
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,2011-12-09,1.25,13113.0,United Kingdom
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09,8.95,13113.0,United Kingdom
541893,581586,20685,DOORMAT RED RETROSPOT,10,2011-12-09,7.08,13113.0,United Kingdom
541894,581587,22631,CIRCUS PARADE LUNCH BOX,12,2011-12-09,1.95,12680.0,France
541895,581587,22556,PLASTERS IN TIN CIRCUS PARADE,12,2011-12-09,1.65,12680.0,France
541896,581587,22555,PLASTERS IN TIN STRONGMAN,12,2011-12-09,1.65,12680.0,France
541897,581587,22728,ALARM CLOCK BAKELIKE PINK,4,2011-12-09,3.75,12680.0,France
541898,581587,22727,ALARM CLOCK BAKELIKE RED,4,2011-12-09,3.75,12680.0,France
541899,581587,22726,ALARM CLOCK BAKELIKE GREEN,4,2011-12-09,3.75,12680.0,France
541900,581587,22730,ALARM CLOCK BAKELIKE IVORY,4,2011-12-09,3.75,12680.0,France
541901,581587,22367,CHILDRENS APRON SPACEBOY DESIGN,8,2011-12-09,1.95,12680.0,France
541902,581587,22629,SPACEBOY LUNCH BOX,12,2011-12-09,1.95,12680.0,France
541903,581587,23256,CHILDRENS CUTLERY SPACEBOY,4,2011-12-09,4.15,12680.0,France
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09,4.95,12680.0,France

In [91]:
#infile['Quantity']=infile.drop([[infile['Quantity']]]== 0)
#df.drop(df.index[2])
infile=infile[infile['Quantity']!=0]
#infile.drop(infile['Quantity'])
infile

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01,4.25,13047.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,2010-12-01,4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01,5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01,5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01,7.95,13047.0,United Kingdom
20,536367,48187,DOORMAT NEW ENGLAND,4,2010-12-01,7.95,13047.0,United Kingdom
21,536368,22960,JAM MAKING SET WITH JARS,6,2010-12-01,4.25,13047.0,United Kingdom
22,536368,22913,RED COAT RACK PARIS FASHION,3,2010-12-01,4.95,13047.0,United Kingdom
23,536368,22912,YELLOW COAT RACK PARIS FASHION,3,2010-12-01,4.95,13047.0,United Kingdom
24,536368,22914,BLUE COAT RACK PARIS FASHION,3,2010-12-01,4.95,13047.0,United Kingdom
25,536369,21756,BATH BUILDING BLOCK WORD,3,2010-12-01,5.95,13047.0,United Kingdom
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01,3.75,12583.0,France
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01,3.75,12583.0,France
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01,3.75,12583.0,France
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01,0.85,12583.0,France
...,...,...,...,...,...,...,...,...
541879,581585,22726,ALARM CLOCK BAKELIKE GREEN,8,2011-12-09,3.75,15804.0,United Kingdom
541880,581585,22727,ALARM CLOCK BAKELIKE RED,4,2011-12-09,3.75,15804.0,United Kingdom
541881,581585,16016,LARGE CHINESE STYLE SCISSOR,10,2011-12-09,0.85,15804.0,United Kingdom
541882,581585,21916,SET 12 RETRO WHITE CHALK STICKS,24,2011-12-09,0.42,15804.0,United Kingdom
541883,581585,84692,BOX OF 24 COCKTAIL PARASOLS,25,2011-12-09,0.42,15804.0,United Kingdom
541884,581585,84946,ANTIQUE SILVER T-LIGHT GLASS,12,2011-12-09,1.25,15804.0,United Kingdom
541885,581585,21684,SMALL MEDINA STAMPED METAL BOWL,12,2011-12-09,0.85,15804.0,United Kingdom
541886,581585,22398,MAGNETS PACK OF 4 SWALLOWS,12,2011-12-09,0.39,15804.0,United Kingdom
541887,581585,23328,SET 6 SCHOOL MILK BOTTLES IN CRATE,4,2011-12-09,3.75,15804.0,United Kingdom
541888,581585,23145,ZINC T-LIGHT HOLDER STAR LARGE,12,2011-12-09,0.95,15804.0,United Kingdom
541889,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,2011-12-09,1.95,15804.0,United Kingdom
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,2011-12-09,2.95,13113.0,United Kingdom
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,2011-12-09,1.25,13113.0,United Kingdom
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09,8.95,13113.0,United Kingdom
541893,581586,20685,DOORMAT RED RETROSPOT,10,2011-12-09,7.08,13113.0,United Kingdom
541894,581587,22631,CIRCUS PARADE LUNCH BOX,12,2011-12-09,1.95,12680.0,France
541895,581587,22556,PLASTERS IN TIN CIRCUS PARADE,12,2011-12-09,1.65,12680.0,France
541896,581587,22555,PLASTERS IN TIN STRONGMAN,12,2011-12-09,1.65,12680.0,France
541897,581587,22728,ALARM CLOCK BAKELIKE PINK,4,2011-12-09,3.75,12680.0,France
541898,581587,22727,ALARM CLOCK BAKELIKE RED,4,2011-12-09,3.75,12680.0,France
541899,581587,22726,ALARM CLOCK BAKELIKE GREEN,4,2011-12-09,3.75,12680.0,France
541900,581587,22730,ALARM CLOCK BAKELIKE IVORY,4,2011-12-09,3.75,12680.0,France
541901,581587,22367,CHILDRENS APRON SPACEBOY DESIGN,8,2011-12-09,1.95,12680.0,France
541902,581587,22629,SPACEBOY LUNCH BOX,12,2011-12-09,1.95,12680.0,France
541903,581587,23256,CHILDRENS CUTLERY SPACEBOY,4,2011-12-09,4.15,12680.0,France
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09,4.95,12680.0,France

In [92]:
#infile.groupby(['InvoiceDate','CustomerID'])
RFM=pd.DataFrame(columns=['R','F','M'])
RFM.head()

Empty DataFrame
Columns: [R, F, M]
Index: []

In [93]:
#F
RFM['F']=infile.groupby(by=['CustomerID'])['InvoiceNo'].nunique()
RFM.head()

              R  F    M
CustomerID
12346.0     NaN  2  NaN
12347.0     NaN  7  NaN
12348.0     NaN  4  NaN
12349.0     NaN  1  NaN
12350.0     NaN  1  NaN

In [94]:
#R
import datetime as dt
NOW = dt.datetime(2011,12,10)
#infile['InvoiceDate']=infile['InvoiceDate'].apply(lambda x:datetime.strptime(x, '%m/%d/%Y %H:%M').strftime('%Y-%m-%d'))
RFM['R'] = infile.groupby('CustomerID').max()['InvoiceDate'].apply( lambda x: (NOW - datetime.strptime(x,'%Y-%m-%d')).days)
RFM['R'].head()

CustomerID
12346.0    326
12347.0      3
12348.0     76
12349.0     19
12350.0    311
Name: R, dtype: int64

In [95]:
#M
M_df=infile[['CustomerID','UnitPrice','Quantity']]
M_df['Sales']=infile['UnitPrice']*infile['Quantity']
RFM['M']=M_df.groupby(by=['CustomerID']).sum()['Sales']
RFM.head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

              R  F        M
CustomerID
12346.0     326  2     0.00
12347.0       3  7  4310.00
12348.0      76  4  1797.24
12349.0      19  1  1757.55
12350.0     311  1   334.40

In [96]:
import numpy as np
quantiles = RFM.quantile(q=[0.25,0.5,0.75])
quantiles

          R    F          M
0.25   17.0  1.0   293.3625
0.50   51.0  3.0   648.0750
0.75  144.0  5.0  1611.7250

In [97]:
quantiles = quantiles.to_dict()
quantiles

{'F': {0.25: 1.0, 0.5: 3.0, 0.75: 5.0},
 'M': {0.25: 293.36250000000007,
  0.5: 648.0750000000002,
  0.75: 1611.7249999999995},
 'R': {0.25: 17.0, 0.5: 51.0, 0.75: 144.0}}

In [0]:
segmented_rfm = RFM

In [0]:
def RScore(x,p,d):
    if x <= d[p][0.25]:
        return 1
    elif x <= d[p][0.50]:
        return 2
    elif x <= d[p][0.75]: 
        return 3
    else:
        return 4
    
def FMScore(x,p,d):
    if x <= d[p][0.25]:
        return 4
    elif x <= d[p][0.50]:
        return 3
    elif x <= d[p][0.75]: 
        return 2
    else:
        return 1

In [0]:
segmented_rfm['r_quartile'] = segmented_rfm['R'].apply(RScore, args=('R',quantiles,))
segmented_rfm['f_quartile'] = segmented_rfm['F'].apply(FMScore, args=('F',quantiles,))
segmented_rfm['m_quartile'] = segmented_rfm['M'].apply(FMScore, args=('M',quantiles,))

In [101]:

segmented_rfm.head()

              R  F        M  r_quartile  f_quartile  m_quartile
CustomerID
12346.0     326  2     0.00           4           3           4
12347.0       3  7  4310.00           1           1           1
12348.0      76  4  1797.24           3           2           1
12349.0      19  1  1757.55           2           4           1
12350.0     311  1   334.40           4           4           3

In [102]:

segmented_rfm['RFMScore'] = segmented_rfm.r_quartile.map(str) \
                            + segmented_rfm.f_quartile.map(str) \
                            + segmented_rfm.m_quartile.map(str)
segmented_rfm.head()

              R  F        M  r_quartile  f_quartile  m_quartile RFMScore
CustomerID
12346.0     326  2     0.00           4           3           4      434
12347.0       3  7  4310.00           1           1           1      111
12348.0      76  4  1797.24           3           2           1      321
12349.0      19  1  1757.55           2           4           1      241
12350.0     311  1   334.40           4           4           3      443

In [103]:
segmented_rfm[segmented_rfm['RFMScore']=='111'].sort_values('M', ascending=False).head(10)

             R    F          M  r_quartile  f_quartile  m_quartile RFMScore
CustomerID
14646.0      2   77  279489.02           1           1           1      111
18102.0      1   62  256438.49           1           1           1      111
17450.0      9   55  187482.17           1           1           1      111
14911.0      2  248  132572.62           1           1           1      111
14156.0     10   66  113384.14           1           1           1      111
17511.0      3   46   88125.38           1           1           1      111
16684.0      5   31   65892.08           1           1           1      111
13694.0      4   60   62653.10           1           1           1      111
15311.0      1  118   59419.34           1           1           1      111
13089.0      3  118   57385.88           1           1           1      111